name: Docker Image CI

on:
  push:
    branches: [ "main" , "feature/*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-docker-demo:v1.2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Docker push
      run: docker push go-docker-demo:v1.2      
